# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ae793f0ac22674c2b78446439aac4ba"
name = "MyOperator"
application_url = "https://mo-cli.vercel.app/"
embedded = true
handle = "myoperator-flask01"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Learn more at
# https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes

scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = ["https://increasingly-sporting-noon-challenging.trycloudflare.com/auth/callback", "https://increasingly-sporting-noon-challenging.trycloudflare.com/auth/shopify/callback", "https://increasingly-sporting-noon-challenging.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
