# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ae793f0ac22674c2b78446439aac4ba"
name = "MyOperator"
application_url = "https://investigate-wallpaper-moss-thus.trycloudflare.com"
embedded = true
handle = "myoperator-flask01"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = ["customers/create"]
  uri = "/webhooks/customers/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Learn more at
# https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes

scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = ["https://investigate-wallpaper-moss-thus.trycloudflare.com/auth/callback", "https://investigate-wallpaper-moss-thus.trycloudflare.com/auth/shopify/callback", "https://investigate-wallpaper-moss-thus.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
